services:
  - type: web
    name: financeflow-app
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn expense_tracker.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false