# Generated by Django 6.1.1 on 2026-09-13 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=6)),
                ('flag', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Auto-created starter category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#10b981', 'Emerald'), ('#0ea5e9', 'Sky'), ('#8b5cf6', 'Violet'), ('#ec4899', 'Pink'), ('#ef4444', 'Red'), ('#f59e0b', 'Amber'), ('#06b6d4', 'Cyan'), ('#3b82f6', 'Blue'), ('#a855f7', 'Purple'), ('#f97316', 'Orange'), ('#14b8a6', 'Teal')], default='#10b981', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('🍔', 'Food'), ('🚗', 'Transport'), ('🏠', 'Rent'), ('💡', 'Utilities'), ('🎬', 'Entertainment'), ('💊', 'Health'), ('🛒', 'Shopping'), ('📚', 'Education'), ('✈️', 'Travel'), ('💰', 'Salary'), ('🎁', 'Gift'), ('📈', 'Investment'), ('💻', 'Subscriptions'), ('🏋️', 'Fitness'), ('☕', 'Coffee'), ('🛍️', 'Retail'), ('🍽️', 'Dining'), ('📱', 'Phone'), ('🎓', 'Tuition'), ('🚌', 'Public Transport'), ('💳', 'Other')], default='💳', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.currency'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'currency', 'month', 'year')},
        ),
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_currencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User currencies',
                'ordering': ['-is_primary', 'currency__code'],
                'unique_together': {('user', 'currency')},
            },
        ),
    ]
