# Generated by Django 6.1.1 on 2026-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_seed_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(blank=True, help_text='Optional — attach a photo or scan of the receipt', null=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
