# Generated by Django 6.1.1 on 2026-09-23 00:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_recurringtransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringtransaction',
            options={'ordering': ['next_run_datetime', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='last_run_date',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='next_run_date',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='start_date',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Optional — stop repeating after this moment', null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='last_run_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='next_run_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the next transaction will be created'),
            preserve_default=False,
        ),
    ]
