# Generated by Django 6.1.1 on 2026-09-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_recurringtransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='runs_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='When the schedule first started (set automatically on save)', null=True),
        ),
    ]
